### ISSUE TITLE
if you think stealing SerenityOS will land you a job

### ISSUE THREAD

**Issue by kvdrrrrr** [AristodamusAdairs/SegueBaseOS#1]
then you're fucking delusional

**Comment by AristodamusAdairs** [comment]
I have given the appropriate license to serenity! I did not stealed anything

**Comment by AristodamusAdairs** [comment]
stay in senses and see ![this](https://github.com/AristodamusAdairs/SegueBaseOS/blob/main/COPYING)

**Comment by AristodamusAdairs** [comment]
And mister if you know DogeCoin was build on bitcoin. That is what I am doing so mind your dirty language

**Comment by kvdrrrrr** [comment]
Ha ha ha !
